### ISSUE TITLE
Need Help !

### ISSUE THREAD

**Issue by metrobim** [SiddharthVenu/Jarvis#1]
Hey there !

I work in a private firm ( construction & infrastructure based ) and I am creating a map based website for users at different hierarchies [ executives, site engineers, planning engineers, designers, architects, etc  ].

I am in the process of upgrading our outdated app and as a part of the process I am using artyom js for voice commands.

The issue is that, it can handle only predefined commands [ you can check the documentation for other details ] and i need the app to be smarter by adopting different strategies for different users.

I went through your app and it internally uses brainshop api. 

The documentation is a bit messy out there and If you can give some insight on how it works [ Algo and other basic details ], it will be of great help !

Thx
pri0ri7y 

you can whatsapp me @ 9840577142

**Comment by sidvenu** [comment]
Hello @metrobim 
Jarvis is an app for conversation, and not smart AI with brainshop. I don't think you can use brainshop for doing things other than replying to people. From what you tell me, I suggest you take a look at IBM Watson (a set of easily avail. tools for AI and Natural Language Processing).

Regards... Sid
